### ISSUE TITLE
fix: navbar should contain link (<a>) elements with the class of "nav-link"

### ISSUE THREAD

**Issue by techieeliot** [gusmontoya/Technical-Documentation-fCC#1]
[Technical Documentation Page tests.docx](https://github.com/gusmontoya/Technical-Documentation-fCC/files/6508384/Technical.Documentation.Page.tests.docx)

•	10. Additionally, the navbar should contain link (<a>) elements with the class of "nav-link". There should be one for every element with the class "main-section".
	•	There should be one .nav-link for every element with the class of "main-section", and every .nav-link should be within #navbar : expected 6 to equal 7
	•	AssertionError: There should be one .nav-link for every element with the class of "main-section", and every .nav-link should be within #navbar : expected 6 to equal 7

**Comment by gusmontoya** [comment]
Solved issue, missing details such as "?" on a <a> and "header". All issues are solved now. I have to pay attention to detail.

**Comment by gusmontoya** [comment]
Solved issue's, missing details such as "?" on a <a> and "header". All issues are solved now. I have to pay attention to detail.
